### ISSUE TITLE
Eficácia do trabalho: Exploração Lunar

### ISSUE THREAD

**Issue by CleitonCardoso** [leandersonandre/itc-exercicios#2]
Professor, to criando essa issue pra questionar se esse exercício é valido: https://github.com/leandersonandre/itc-exercicios/blob/master/001-trabalho-exploracao-lunar.md.

Porque:

* A maior parte do problema não me parece ter relação com Teoria da Computação. Uma vez que a maior dificuldade está em ler e interpretar linha por linha do arquivo de teste.

* O arquivo de teste parece propositalmente complexo para dificultar o trabalho, exemplo:

  - Não tem necessidade de informar o número de vértices, este caso tem obviamente 4 vértices:

```
1 . * *            
* 2 . *
* * 3 .
* * * 4
```

Se tivesse 5 vértices:

```
1 . * * *            
* 2 . * *
* * 3 . *
* * * 4 .
* * * * 5 
```

Além disso, a mesma tabela poderia ser expressada dessa forma:

  | 1 | 2 | 3 | 4
-- | -- | -- | -- | --
1 | 0 | 0 | 0 | 0
2 | 1 | 0 | 0 | 0
3 | 0 | 1 | 0 | 0
4 | 0 | 0 | 1 | 0

Onde o valor 1 indica que o caminho é válido, quando a seta aponta para direita, o eixo dominante é o X, quando aponta para a esquerda, o eixo dominante é o Y;

Adaptando a segunda tabela do exercício teríamos:

  | 6 | y | % | &
-- | -- | -- | -- | --
6 | 0 | 0 | 0 | 0
y | 0 | 0 | 1 | 0
% | 1 | 1 | 0 | 0
& | 0 | 0 | 1 | 0

A minha impressão é que eu to quebrando a cabeça pra resolver um problema que não é nem o foco da disciplina.

Isso não vai ser justificativa para não entregar o trabalho, já foi feito. Porém gostaria de garantir que não haja frustração ao resolver os trabalhos pois esse tipo de problema já resolvemos bastante nas matérias de Algoritmos e POO.

**Comment by leandersonandre** [comment]
Olá Cleiton,

É super válido questionar, esta é a melhor maneira de adquirir mais conhecimentos.
Segue minhas considerações.

> A maior parte do problema não me parece ter relação com Teoria da Computação.

O problema que solicitei para resolver é conhecido muito conhecido na área de problemas computacionais, onde deve verificar em um grafo direcionado se existe um caminho de *i* até *j* ([Descrição formal do problema]( http://www.ccs.neu.edu/home/rjw/csu390-sp06/LectureMaterials/P-Examples.pdf)). Sendo o primeiro passo para resolver uma gama de problemas complexos, por exemplo o [caixeiro viajante](http://www.math.uwaterloo.ca/tsp/). A Teoria da Computação estuda exatamente como resolver estes tipos de problemas, pois a grande maioria dos problemas do mundo real não tem como resolver. Se souber como resolver me diz, essa resposta vale 1 milhão de reais =D  [fonte](http://www.claymath.org/millennium-problems/p-vs-np-problem).

>  Uma vez que a maior dificuldade está em ler e interpretar linha por linha do arquivo de teste.

Uma vez que se encontra no 4º ano de uma faculdade de computação, a programação de algoritmos, ler e escrever arquivos não pode ser a maior dificuldade. 

>O arquivo de teste parece propositalmente complexo para dificultar o trabalho, exemplo:
    * Não tem necessidade de informar o número de vértices, este caso tem obviamente 4 vértices:

Realmente não há a necessidade de informar o número de vértices. Porém conhecer antecipadamente a quantidade de vértices torna mais simples a criação da matriz em memória, uma vez que não é necessário fazer *split* da  primeira linha da matriz pra descobrir a quantidade de vértices.

> Além disso, a mesma tabela poderia ser expressada dessa forma:

Um grafo direcionado não possui eixo dominante e não pode ser rotacionado. Deve ser respeitado a sequencia das linhas e colunas informadas.

Portanto, estas duas tabelas são completamente diferente. Sugestão, monte os grafos, e analise o resultado.

  | 1 | 2 | 3 | 4
-- | -- | -- | -- | --
1 | 0 | 1 | 0 | 0
2 | 0 | 0 | 1 | 0
3 | 0 | 0 | 0 | 1
4 | 0 | 0 | 0 | 0

  | 1 | 2 | 3 | 4
-- | -- | -- | -- | --
1 | 0 | 0 | 0 | 0
2 | 1 | 0 | 0 | 0
3 | 0 | 1 | 0 | 0
4 | 0 | 0 | 1 | 0


> A minha impressão é que eu to quebrando a cabeça pra resolver um problema que não é nem o foco da disciplina.

O objetivo da disciplina é exatamente este, resolver problemas. Você está no caminho certo =D


>  Porém gostaria de garantir que não haja frustração ao resolver os trabalhos pois esse tipo de problema já resolvemos bastante nas matérias de Algoritmos e POO.

Grafos é uma estrutura de dados básica na computação. Pode ser utilizado para representar qualquer tipo de problema, até os menos óbvios.  Por isso, é muito estudada e utilizadas em diferentes disciplinas.  Porém resolver o problema com o grafo nas disciplinas de algoritmos e POO não é o mesmo que saber por que é possível resolver este problema. Ou indo um pouco mais além, por que não é possível resolver um determinado problema. Um exemplo super simples, crie uma matriz com mais de 100 000 000 vértices e verifique se seu algoritmo é capaz de resolver.

Qualquer dúvida, sugestão, entre em contato,
Estamos aqui para ajudar =D
